language: python
python:
- 3.6
- 3.5
install:
    - pip install -r requirements_dev.txt
    - pip install -U tox-travis
script:
    - tox
    - coverage run --source qi_irida_utils -m py.test tests/
    - coverage report -m
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: happy_khan
  password:
    secure: lXWMIhbt9PKVJWTPQtLFb80XXxMrQVuNO2eqQsj0IFvX4yjhuv33QNPerBNU2ZYRXJX8aLQ+Ik/IxFceFcLAnAqEMzwxKPWdm0v+FQFf0sd6c1OTNNt+a3/Aqh2OGUq9tpmovkPeFc1ssYxGzyPtAZtbHcS9lw8Hw+uIqBhqn35gugW1AcVZFvx2qQTEfbg4+uPcPzADGs0WP9xaU8Rii+8Soj8ZQjy7rxIQqpiZy0ozbuQpUrzfdnkbP6XFW3izeBVPAuNInCLHLJuYlHSXq0AM5jSNsvvQsc2dzKu/WMGp9t4IasVdm/l/Elq5rGbdkxtvUBcQM4YfRYBY2dse7Wefxpl2fYMV63/OFmbIAfUU4cjQOVl+dOjvB+KCrpeV9OfkxADTiSjqUWDF76SvvwEnXc8jb7OGMyAYyo5i0EIvCGpib77qHDRf/4PbVhu5U5QsNlRE88R3krk+eBN6Am6NnVRm4VujMBv9mxggbTAqiRPLdLMPAiIgy0eZJLaFjowe2VaaTR+EXERT9KXASCy/ssVT3wiU3MtS9eRi+rI4revpf5uGn+9SgokhAOjxNgfLAcEosZJaN7X067mUKhSAa9TameM0RNCMqKoEfyqIZ20sUn0K98ixxHxGlrGK3fwAPeK+D712zgFPqh583sfI9QmPITTMBt9O4vjfH8Y=
  on:
    tags: true
    repo: happykhan/qi_irida_utils
    python: 3.6
after_success:
- coveralls
